# **ICE-2: Regular Expressions**

**Instructions**:
1. Wherever you are asked to code, insert a text block below your code block and explain what you have coded as per your own understanding.
2. If the code is provided by us, execute it, and add below a text block and provide your explanation in your own words.
3. Submit both the .ipynb and pdf files to canvas.
4. **The similarity score should be less than 15%.**

Python includes a builtin module called `re` which provides regular expression matching operations (Click [here](https://docs.python.org/3/library/re.html) for the official module documentation). Once the module is imported into your code, you can use all of the available capabilities for performing pattern-based matching or searching using regular expressions.

In [103]:
import re

def apply_regex(data, pattern):
  for text in data:
    if re.fullmatch(pattern, text):
      print(f"Test string {text} accepted.")
    else:
      print(f"Test string {text} failed!")

We have imported the re module.Then we have created a user defined function called apply_regex, which will compare the string to our regular expression and return if the string is accepted or failed.

Let's write a simple regular expression for matching binary strings.

In [104]:
# find binary strings
test_strings = ["0", "1", "dog", "hello, world", "123", "00", "10101010111"]
binary_pattern = r'[0-1]+'
apply_regex(test_strings, binary_pattern)

Test string 0 accepted.
Test string 1 accepted.
Test string dog failed!
Test string hello, world failed!
Test string 123 failed!
Test string 00 accepted.
Test string 10101010111 accepted.


0 and 1 are accepted because they are binary strings.
dog and hello failed becuase they are not binary strings.
123 failed because binary strings only contain 0 and 1s.
00 and 10101010111 are accepted because they are binary strings.

Now, how about for matching 24-bit hexadecimal codes?

In [105]:
# find 24-bit hexadecimal color codes
test_strings = ["#F0F8FF", "#FFF", "#00FFFFF", "#2980BD", "#FAEBD7"]
hexcode_pattern = r'\#[0-9A-F]{5,6}'
apply_regex(test_strings, hexcode_pattern)

Test string #F0F8FF accepted.
Test string #FFF failed!
Test string #00FFFFF failed!
Test string #2980BD accepted.
Test string #FAEBD7 accepted.


F0F8FF got accepted because it is 24-bit hexadecimal.
FFF failed beacuase it is not 24-bit.
00FFFFF failed beacuase it is not 24-bit.
2980BD and FAEBD7 got accepted beacause they are 24-bit hexadecimal color codes.

#### **Question 1. (5 points)** 

*Identify what types of strings the regular expression in the below code block represents?* 

In [106]:
# All you need to do is run this code block, analyze the output and answer the associated question.
re_pattern = r'(\([0-9][0-9][0-9]\)\s)?[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]'
test_strings = ["00", "999-999-9999", "(111) 111-1111", "(111)111-1111", "989-1830", "241/131/103", "(182).1903.1021", "(101).101.1001"]
apply_regex(test_strings, re_pattern)

Test string 00 failed!
Test string 999-999-9999 failed!
Test string (111) 111-1111 accepted.
Test string (111)111-1111 failed!
Test string 989-1830 accepted.
Test string 241/131/103 failed!
Test string (182).1903.1021 failed!
Test string (101).101.1001 failed!


The type of strings that are allowed are of 2 types:
1.(3 digits) space 3 digits - 4 digits OR (xxx) xxx-xxxx where x is a digit from 0 to 9.
2.3 digits - 4 digits OR xxx-xxxx where x is a digit from 0 to 9.
rest all the types of strings are rejected.
We can see that only (111) 111-1111 and 989-1830 are accepted rest all are rejected.

#### **Question 2. (10 points)**

*Modify the regular expression (used in Q1.) to also accept strings that follow the format `xxx-xxx-xxxx` where `x` is a digit between 0 to 9?*

In [107]:
# Replace the modified regular expression in the code snippet used in Question 1
# Add your code below this comment and execute your code
re_pattern = r'(\([0-9][0-9][0-9]\)\s)?[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]|[0-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]'
test_strings = ["00", "999-999-9999", "(111) 111-1111", "(111)111-1111", "989-1830", "241/131/103", "(182).1903.1021", "(101).101.1001","123-123-1234"]
apply_regex(test_strings, re_pattern)


Test string 00 failed!
Test string 999-999-9999 accepted.
Test string (111) 111-1111 accepted.
Test string (111)111-1111 failed!
Test string 989-1830 accepted.
Test string 241/131/103 failed!
Test string (182).1903.1021 failed!
Test string (101).101.1001 failed!
Test string 123-123-1234 accepted.


Using the disjunction pipe |, I have modified the code to accept the strings of the format xxx-xxx-xxxx where x is a digit from 0 to 9.We can check that as 123-123-1234 is accepted.

#### **Question 3. (20 points)**

*Modify the regular expression (used in Q2.) to also accept strings that are of the form `(xxx) xxx-xxxx` and `(xxx)xxx-xxxx` where `x` is a digit between 0 to 9?*

In [108]:
# Replace the modified regular expression in the code snippet used in Question 2
# Add your code below this comment and execute your code
re_pattern = r'(\([0-9][0-9][0-9]\)\s?)?[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]|[0-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]'
test_strings = ["00", "999-999-9999", "(111) 111-1111", "(111)111-1111", "989-1830", "241/131/103", "(182).1903.1021", "(101).101.1001","123-123-1234"]
apply_regex(test_strings, re_pattern)


Test string 00 failed!
Test string 999-999-9999 accepted.
Test string (111) 111-1111 accepted.
Test string (111)111-1111 accepted.
Test string 989-1830 accepted.
Test string 241/131/103 failed!
Test string (182).1903.1021 failed!
Test string (101).101.1001 failed!
Test string 123-123-1234 accepted.


I have modified the code to accept the strings of the form (xxx) xxx-xxxx and (xxx)xxx-xxxx by adding the ? after \s(which means it will accept both strings with and without the space).The code was already accepting the (xxx) xxx-xxxx type of string as (111) 111-1111. We can verify for the (xxx)xxx-xxxx type as (111)111-1111 is also accepted. 

#### **Question 4. (20 points)**

*Modify the regular expression (used in Q3.) to accept strings that have the format `(xxx)-xxx-xxxx` and `(xxx).xxx.xxxx` but reject strings that are of the format `(xxx)/xxx.xxxx` where `x` is a digit between 0 to 9?*

In [109]:
# Replace the modified regular expression in the code snippet used in Question 3
# Add your code below this comment and execute your code

re_pattern = r'(\([0-9][0-9][0-9]\)\s?)?[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]|[0-9][0-9][0-9]-[0-9][0-9][0-9]-[0-9][0-9][0-9][0-9]|\([0-9][0-9][0-9]\)[^/][0-9][0-9][0-9].[0-9][0-9][0-9][0-9]'
test_strings = ["00", "999-999-9999", "(111) 111-1111", "(111)111-1111", "989-1830", "241/131/103", "(182).1903.1021", "(101).101.1001","123-123-1234","(111)-111-1111","(111).111.1111","(111)/111.1111"]
apply_regex(test_strings, re_pattern)

Test string 00 failed!
Test string 999-999-9999 accepted.
Test string (111) 111-1111 accepted.
Test string (111)111-1111 accepted.
Test string 989-1830 accepted.
Test string 241/131/103 failed!
Test string (182).1903.1021 failed!
Test string (101).101.1001 accepted.
Test string 123-123-1234 accepted.
Test string (111)-111-1111 accepted.
Test string (111).111.1111 accepted.
Test string (111)/111.1111 failed!


I have modified the regular expression to accept the strings of the format (xxx)-xxx-xxxx and (xxx).xxx.xxxx but reject the strings of the format (xxx)/xxx.xxxx where x is a digit betweeen 0 to 9. We can verify this as the strings (101).101.1001 , (111)-111-1111 and (111).111.1111 are accepted but the string (111)/111.1111 is failed. 

---

## **Using regular expressions based pattern matching on real world text**

For the purposes of demonstration, here's a dummy paragraph of text. A few observations here:
* The text has multiple paragraphs with each paragraph having more than one sentence. 
* Some of the words are capitalized (first letter is in uppercase followed by lowercase letters). 

In [110]:
text = """Here is the First Paragraph and this is the First Sentence. here is the Second Sentence. now is the Third Sentence. this is the Fourth Sentence of the first paragaraph. this paragraph is ending now with a Fifth Sentence.
Now, it is the Second Paragraph and its First Sentence. here is the Second Sentence. now is the Third Sentence. this is the Fourth Sentence of the second paragraph. this paragraph is ending now with a Fifth Sentence.
Finally, this is the Third Paragraph and is the First Sentence of this paragraph. here is the Second Sentence. now is the Third Sentence. this is the Fourth Sentence of the third paragaraph. this paragraph is ending now with a Fifth Sentence.
4th paragraph is not going to be detected by either of the regex patterns below.
"""

print(text)

Here is the First Paragraph and this is the First Sentence. here is the Second Sentence. now is the Third Sentence. this is the Fourth Sentence of the first paragaraph. this paragraph is ending now with a Fifth Sentence.
Now, it is the Second Paragraph and its First Sentence. here is the Second Sentence. now is the Third Sentence. this is the Fourth Sentence of the second paragraph. this paragraph is ending now with a Fifth Sentence.
Finally, this is the Third Paragraph and is the First Sentence of this paragraph. here is the Second Sentence. now is the Third Sentence. this is the Fourth Sentence of the third paragaraph. this paragraph is ending now with a Fifth Sentence.
4th paragraph is not going to be detected by either of the regex patterns below.



The text has been printed.

The following code block shows a regular expression that matches only those strings that:
1. are at the start of a line and
2. the string does not start with a number or a whitespace

`re.findall()` finds all matches of the pattern in the text under consideration. The output is a list of strings that matched.

In [111]:
re_pattern1 = r'^[^0-9 ]+'
print(re.findall(re_pattern1, text, re.MULTILINE))

['Here', 'Now,', 'Finally,']


only three strings satisfy the condition, so they are printed.

Further, the regular expression defined below matches two consecutive words that are capitalized.

In [112]:
re_pattern2 = r'[A-Z][a-z]+ [A-Z][a-z]+'
print(re.findall(re_pattern2, text))

['First Paragraph', 'First Sentence', 'Second Sentence', 'Third Sentence', 'Fourth Sentence', 'Fifth Sentence', 'Second Paragraph', 'First Sentence', 'Second Sentence', 'Third Sentence', 'Fourth Sentence', 'Fifth Sentence', 'Third Paragraph', 'First Sentence', 'Second Sentence', 'Third Sentence', 'Fourth Sentence', 'Fifth Sentence']


All the matches for two consecutive capitalized words have been printed.



Following is a text excerpt on "Inaugural Address" taken from the website of the [Joint Congressional Committee on Inaugural Ceremonies](https://www.inaugural.senate.gov/inaugural-address/):

In [113]:
inau_text="""The custom of delivering an address on Inauguration Day started with the very first Inauguration—George Washington’s—on April 30, 1789. After taking his oath of office on the balcony of Federal Hall in New York City, Washington proceeded to the Senate chamber where he read a speech before members of Congress and other dignitaries. His second Inauguration took place in Philadelphia on March 4, 1793, in the Senate chamber of Congress Hall. There, Washington gave the shortest Inaugural address on record—just 135 words —before repeating the oath of office.
Every President since Washington has delivered an Inaugural address. While many of the early Presidents read their addresses before taking the oath, current custom dictates that the Chief Justice of the Supreme Court administer the oath first, followed by the President’s speech.
William Henry Harrison delivered the longest Inaugural address, at 8,445 words, on March 4, 1841—a bitterly cold, wet day. He died one month later of pneumonia, believed to have been brought on by prolonged exposure to the elements on his Inauguration Day. John Adams’ Inaugural address, which totaled 2,308 words, contained the longest sentence, at 737 words. After Washington’s second Inaugural address, the next shortest was Franklin D. Roosevelt’s fourth address on January 20, 1945, at just 559 words. Roosevelt had chosen to have a simple Inauguration at the White House in light of the nation’s involvement in World War II.
In 1921, Warren G. Harding became the first President to take his oath and deliver his Inaugural address through loud speakers. In 1925, Calvin Coolidge’s Inaugural address was the first to be broadcast nationally by radio. And in 1949, Harry S. Truman became the first President to deliver his Inaugural address over television airwaves.
Most Presidents use their Inaugural address to present their vision of America and to set forth their goals for the nation. Some of the most eloquent and powerful speeches are still quoted today. In 1865, in the waning days of the Civil War, Abraham Lincoln stated, “With malice toward none, with charity for all, with firmness in the right as God gives us to see the right, let us strive on to finish the work we are in, to bind up the nation’s wounds, to care for him who shall have borne the battle and for his widow and his orphan, to do all which may achieve and cherish a just and lasting peace among ourselves and with all nations.” In 1933, Franklin D. Roosevelt avowed, “we have nothing to fear but fear itself.” And in 1961, John F. Kennedy declared, “And so my fellow Americans: ask not what your country can do for you—ask what you can do for your country.”
Today, Presidents deliver their Inaugural address on the West Front of the Capitol, but this has not always been the case. Until Andrew Jackson’s first Inauguration in 1829, most Presidents spoke in either the House or Senate chambers. Jackson became the first President to take his oath of office and deliver his address on the East Front Portico of the U.S. Capitol in 1829. With few exceptions, the next 37 Inaugurations took place there, until 1981, when Ronald Reagan’s Swearing-In Ceremony and Inaugural address occurred on the West Front Terrace of the Capitol. The West Front has been used ever since."""



inau_text conatins the text excerpt on "Inaugural Address"

#### **Question 5a. (20 points)**

*Identify all the capitalized words in the "Inaugural Address" excerpt and write a regular expression that finds all occurrences of such words in the text. Then, run the Python code snippet to automatically display the matched strings according to the pattern.*.

NOTE: You can use the *re.findall()* method as demonstrated in the example before this exercise.

In [114]:
# Write your code below these comments and execute your code
# HINT: You may need to tweak the use of capture groups to NOT capture partial matches
# For e.g. 'New York' instead of 'New', 'York')
re_pat = r'[A-Z][a-z]+ [A-Z][a-z]+|[A-Z][a-z]+'
print(re.findall(re_pat, inau_text))


['The', 'Inauguration Day', 'Inauguration', 'George Washington', 'April', 'After', 'Federal Hall', 'New York', 'City', 'Washington', 'Senate', 'Congress', 'His', 'Inauguration', 'Philadelphia', 'March', 'Senate', 'Congress Hall', 'There', 'Washington', 'Inaugural', 'Every President', 'Washington', 'Inaugural', 'While', 'Presidents', 'Chief Justice', 'Supreme Court', 'President', 'William Henry', 'Harrison', 'Inaugural', 'March', 'He', 'Inauguration Day', 'John Adams', 'Inaugural', 'After Washington', 'Inaugural', 'Franklin', 'Roosevelt', 'January', 'Roosevelt', 'Inauguration', 'White House', 'World War', 'In', 'Warren', 'Harding', 'President', 'Inaugural', 'In', 'Calvin Coolidge', 'Inaugural', 'And', 'Harry', 'Truman', 'President', 'Inaugural', 'Most Presidents', 'Inaugural', 'America', 'Some', 'In', 'Civil War', 'Abraham Lincoln', 'With', 'God', 'In', 'Franklin', 'Roosevelt', 'And', 'John', 'Kennedy', 'And', 'Americans', 'Today', 'Presidents', 'Inaugural', 'West Front', 'Capitol', 'Un

My code give the strings such as George Washington, New York, Supreme Court, Chief Justice,etc together and also displays the single capitalized words such as The, April,etc. I am first searching for pair of consecutive words for each words and if the next word is not capital I am storing the current capital term separately.

#### **Question 5b. (25 points)**

*Identify all the dates in the "Inaugural Address" excerpt and write a regular expression that finds all occurrences of the dates in the text. Then, run the Python code snippet to automatically display a list of all such dates identified.*

NOTE: You can use the *re.findall()* method as demonstrated in the example before this exercise.

In [115]:
# Write your code below these comments and execute your code
# HINT: You may need to tweak the use of capture groups to NOT capture partial matches
# For e.g. 'April 20, 1945' instead of 'April', '20')
re_pat = r'[A-Z][a-z]+ [0-9][0-9]*\, [1-9][0-9][0-9][0-9]|[1-9][0-9][0-9][0-9]'
print(re.findall(re_pat, inau_text))

['April 30, 1789', 'March 4, 1793', 'March 4, 1841', 'January 20, 1945', '1921', '1925', '1949', '1865', '1933', '1961', '1829', '1829', '1981']


My code is checking and displaying the dates in the format Month Day, Year. My code also check for the years who do not have day and month as they also signify some kind of date. If the strings with only years is not required we can just modify the re_pat by removing the disjoint condition and [1-9][0-9][0-9][0-9] in the last part. I have done the same thing in the below code.

In [116]:
re_pat = r'[A-Z][a-z]+ [0-9][0-9]*\, [1-9][0-9][0-9][0-9]'
print(re.findall(re_pat, inau_text))

['April 30, 1789', 'March 4, 1793', 'March 4, 1841', 'January 20, 1945']


My code is checking and displaying the dates in the format Month Day, Year.

---